# Generated by Django 4.0.5 on 2022-09-11 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_key', models.TextField()),
                ('dropbox_token', models.TextField(blank=True, help_text='Dropbox access token', null=True)),
                ('default_storage', models.CharField(choices=[(None, '(Not selected)'), ('DX', 'Dropbox')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='encryptionkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='DropboxAccess',
        ),
        migrations.DeleteModel(
            name='EncryptionKey',
        ),
    ]
