version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker_utils/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
#  redis:
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#  celery:
#    build:
#      context: .
#      dockerfile: celery.Dockerfile
#    environment:
#      - DJANGO_SETTINGS_MODULE
#    volumes:
#      - .:/code
  web:
    build: .
    environment:
      - SECRET_KEY
      - RELOAD
      - DEBUG
    command: ./utils/startup.sh
    volumes:
      - .:/code
      - ./docker_utils/web:/code/utils
    ports:
      - "8000:8000"
    depends_on:
      - db
