# Generated by Django 4.0.5 on 2022-08-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky_write_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageobject",
            name="name_iv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="storageobject",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="sky_write_app.storageobject",
            ),
        ),
        migrations.AlterField(
            model_name="storageobject",
            name="name",
            field=models.TextField(),
        ),
    ]
