# Generated by Django 4.0.5 on 2022-09-19 03:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sky_write_app",
            "0002_storageobject_name_iv_alter_storageobject_folder_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="storageobject",
            name="file_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
