# Generated by Django 4.0.5 on 2022-09-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky_write_app", "0003_storageobject_file_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageobject",
            name="content_iv",
            field=models.TextField(blank=True, null=True),
        ),
    ]
