# Generated by Django 4.0.5 on 2022-10-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky_write_app", "0004_storageobject_content_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageobject",
            name="ordering_parameter",
            field=models.DecimalField(decimal_places=11, default=0, max_digits=26),
            preserve_default=False,
        ),
    ]
