# Generated by Django 4.0.5 on 2022-11-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sky_write_app", "0005_storageobject_ordering_parameter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageobject",
            name="ordering_parameter",
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=26),
        ),
    ]
